### ISSUE TITLE
MVP of app

### ISSUE THREAD

**Issue by owocki** [gitcoinco/ios#2]
i want it to be as easy to find paid work in open source as it is for an uber driver to be able to pull down driving work from the cloud.  

of course the comparison to uber is not perfect, because uber is a centralized institution, and gitcoin is decentralized and hopefully owned/supported by it's users... someday at least.

right now the iOS app (screenshots here => https://github.com/gitcoinco/ios ) has only a very rudimentary swipe left / right interface for swiping through work.  i think that MVP is:
- ability to enter your email address
- ability to enter your skills (for me, python, html, web3, etc)
- push notifications once a week when new work is available.
- app is smart enough to only serve you work you haven't seen before, and to only serve you work inside your domain / expertise
- introductory email to repo maintainer is sent when you swipe right on a project.

**Comment by jwaggs** [comment]
In regards to my comments under issue #1 -- I've figured out why it wasn't loading any of those draggable views so I've got the app working again. Also, the duplicate definitions that I referenced appear to actually be a bug specific to Xcode 9.0.1 - so that issue wasn't worth digging into. After looking through the code I may just try to build on it instead of rewriting it to save some time for now. 

As far as email input goes - I'm wondering what your thoughts were. Are we looking to use OAuth and have them sign in to a GitHub account? Or did you actually just want them to punch in their email real quick and be done with it?

For entering skills - I'm trying to find a preexisting set of languages/tags that GitHub uses. Where can I find this?

Also, I can't seem determine what the bounty identifier is in the data that is returned. How can I determine the id of a bounty when I grab them all?

**Comment by jwaggs** [comment]
@owocki - I'd definitely like your feedback on some of the above questions before I continue forward. I started a fresh rewrite of the repository over the weekend but would like your input on those things before continuing forward so that I can best address the vision for the app and so that we don't throw out what I take time to write. Thanks

**Comment by owocki** [comment]
im at ethereum devcon this week. can we sync up this weekend / early next week?  there are others interested in doing the work, so i def don't want you to get too ahead of yourself working on this before we have a chance to sync.

**Comment by jwaggs** [comment]
Ok. We can definitely sync up whenever. I'll stop development for now then. I've got a rewrite going in swift that added a table view for all the bounties so you can view them all in one place and was going to start writing in the ability to search by type, and sort based on fields and other things but I'll just wait to hear more info then so I don't end up throwing away a bunch of work.

**Comment by patgoley** [comment]
Any updates on this? I'd love to help out!

**Comment by owocki** [comment]
progress is ongoing on https://github.com/gitcoinco/ios/pull/3 -- @cheneveld has been hacking away

**Comment by patgoley** [comment]
@owocki Awesome, thanks. I suppose there won't be any bounties until the MVP is done?

**Comment by owocki** [comment]
MVP is close (@cheneveld dont kill me for saying that).  but until that's out, there are bounties available on the web repo. 

@patgoley whats your skillset

**Comment by patgoley** [comment]
@owocki iOS, Android, and web. I noticed there isn't an Android client yet so would be happy to discuss that if you're interested. I'll gladly take a stab at some of the web issues in the meantime. Thanks!

**Comment by owocki** [comment]
word;  hit me up in mid December about the android client.  will have cycles to think on it then.

**Comment by owocki** [comment]
@patgoley any interest in this ? https://github.com/gitcoinco/ios/issues/4

**Comment by patgoley** [comment]
@owocki Absolutely, will take a stab this evening. Should I branch off of #3 or wait until that branch is merged? Would like to avoid major merge conflicts if possible. (cc @cheneveld)

**Comment by owocki** [comment]
sweet @patgoley do you have a portfolio we could look at?  dont want to waste your time if your skillset is way more dev than design

defer to the both of you.

**Comment by patgoley** [comment]
@owocki Oh, my fault. I thought you needed someone to implement the design, but I see now you need the rest of the designs fleshed out. I'm afraid I'm not much of a designer, so I'll probably pass on that issue. Thanks though, I'll look through some other issues.

**Comment by owocki** [comment]
thx for letting us know 👍
